<a href="https://colab.research.google.com/github/shaikhshoeb8791-bot/Data-Cleaning-Project/blob/main/SQL_Project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Dataset for Data Analytics (2).xlsx to Dataset for Data Analytics (2).xlsx

In [4]:
import pandas as pd
import sqlite3

In [5]:
import pandas as pd
import sqlite3

In [7]:
import os

os.listdir()

['.config', 'Dataset for Data Analytics (2).xlsx', 'sample_data']

In [8]:
import os

os.listdir()

['.config', 'Dataset for Data Analytics (2).xlsx', 'sample_data']

In [9]:
import pandas as pd

df = pd.read_excel("Dataset for Data Analytics (2).xlsx")

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [10]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [12]:
import sqlite3

conn = sqlite3.connect("project.db")

In [13]:
df.to_sql("data", conn, if_exists="replace", index=False)

1200

In [14]:
query = "SELECT * FROM data"
pd.read_sql(query, conn).head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [15]:
query = """
SELECT * FROM data
WHERE df.columns[0] IS NOT NULL
"""
pd.read_sql(query, conn).head()

DatabaseError: Execution failed on sql '
SELECT * FROM data
WHERE df.columns[0] IS NOT NULL
': near "[0]": syntax error

In [16]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [19]:
query = "SELECT * FROM data"
pd.read_sql(query, conn).head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [20]:
query = """
SELECT * FROM data
WHERE Quantity > 2
"""
pd.read_sql(query, conn)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
2,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
3,ORD200007,2023-05-12 00:00:00,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
4,ORD200009,2023-11-21 00:00:00,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,ORD201191,2025-02-10 00:00:00,C44148,Desk,4,376.43,809 Main St,Gift Card,Pending,TRK67872709,5,WINTER15,Instagram,1505.72
701,ORD201192,2024-02-28 00:00:00,C72007,Chair,3,432.85,999 Main St,Online,Pending,TRK16240916,4,None,Instagram,1298.55
702,ORD201194,2023-11-19 00:00:00,C29885,Printer,3,189.44,725 Main St,Cash,Pending,TRK62067865,4,FREESHIP,Email,568.32
703,ORD201198,2024-08-22 00:00:00,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
704,ORD201199,2023-06-11 00:00:00,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [21]:
query = """
SELECT * FROM data
ORDER BY TotalPrice DESC
"""
pd.read_sql(query, conn).head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200789,2023-08-17 00:00:00,C57276,Tablet,5,691.28,183 Main St,Online,Delivered,TRK75899752,10,SAVE10,Email,3456.40
1,ORD201122,2023-06-07 00:00:00,C38840,Monitor,5,678.19,766 Main St,Online,Returned,TRK32496970,8,None,Facebook,3390.95
2,ORD200632,2023-05-02 00:00:00,C67260,Laptop,5,678.16,463 Main St,Gift Card,Delivered,TRK38229104,7,WINTER15,Facebook,3390.80
3,ORD200469,2023-11-26 00:00:00,C13877,Chair,5,676.98,893 Main St,Cash,Cancelled,TRK17254691,5,None,Facebook,3384.90
4,ORD200328,2023-02-28 00:00:00,C18404,Tablet,5,674.04,546 Main St,Online,Cancelled,TRK89401624,7,SAVE10,Google,3370.20

In [23]:
query = """
SELECT Product, SUM(Quantity) AS Total_Quantity
FROM data
GROUP BY Product
ORDER BY Total_Quantity DESC
"""
pd.read_sql(query, conn)

   Product  Total_Quantity
0    Chair             562
1  Printer             542
2   Laptop             535
3     Desk             508
4   Tablet             497
5  Monitor             480
6    Phone             411

In [25]:
query = """
SELECT SUM(TotalPrice) AS Total_Revenue
FROM data
"""
pd.read_sql(query, conn)

   Total_Revenue
0     1264761.96

In [26]:
query = """
SELECT AVG(TotalPrice) AS Avg_Order_Value
FROM data
"""
pd.read_sql(query, conn)

   Avg_Order_Value
0        1053.9683

In [27]:
query = """
SELECT Product, SUM(TotalPrice) AS Revenue
FROM data
GROUP BY Product
ORDER BY Revenue DESC
LIMIT 5
"""
pd.read_sql(query, conn)

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41

In [28]:
query = """
SELECT PaymentMethod, COUNT(*) AS Orders
FROM data
GROUP BY PaymentMethod
ORDER BY Orders DESC
"""
pd.read_sql(query, conn)

  PaymentMethod  Orders
0        Online     258
1          Cash     246
2   Credit Card     234
3    Debit Card     232
4     Gift Card     230